station:

  initial_position: 500          # (mm)
  initial_angle: -10             # (degrees)
  final_position: 0
  final_angle: 0
  continous_measurement: false
  linear_step: 50
  angular_step: 5
  offset: 200

  lidar_scans: 100
  camera_images: 5

  rplidar:
    topic: "scan"
  
  rplidar_corrected:
    topic: "scan_corrected"

  camera_astra:
    info_topic:  "camera/color/camera_info"
    color_topic: "camera/color/image_raw"
    depth_topic: "camera/depth/image_raw"
    ir_topic:    "camera/ir/image_raw"

  serial:
    port: "/dev/ttyUSB0"
    baudrate: 115200
