station:

  initial_position: 1500         # (mm)
  initial_angle: -5              # (degrees)
  final_position: 1300
  final_angle: 0
  continous_measurement: false
  linear_step: 50
  angular_step: 5
  offset: 200

  lidar_rate: 100
  camera_rate: 2

  rplidar:
    topic: "scan"

  camera_astra:
    cloud_topic:  "camera/depth/points"
    color_topic: "camera/color/image_raw"
    depth_topic: "camera/depth/image_raw"
    ir_topic:    "camera/ir/image_raw"

  serial:
    port: "/dev/station"
    baudrate: 115200
